// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNrcDjbmXx6-IT5wSijhya0rn9MYXlc6A',
    appId: '1:905253298603:web:500612cf1284af5b3072ee',
    messagingSenderId: '905253298603',
    projectId: 'doctor-test-5ddc4',
    authDomain: 'doctor-test-5ddc4.firebaseapp.com',
    storageBucket: 'doctor-test-5ddc4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUDDHaskFfoxVIDWb0WRfLilYSjWDSpI',
    appId: '1:905253298603:android:955786ed24f896073072ee',
    messagingSenderId: '905253298603',
    projectId: 'doctor-test-5ddc4',
    storageBucket: 'doctor-test-5ddc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmo9K-H-4IIR1ITHAET2aXA_uDThzSAY',
    appId: '1:905253298603:ios:8dfd728f0cd27a333072ee',
    messagingSenderId: '905253298603',
    projectId: 'doctor-test-5ddc4',
    storageBucket: 'doctor-test-5ddc4.appspot.com',
    iosClientId: '905253298603-tblfpfo5khko3tsvkrrt7aguqv7ekc3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmo9K-H-4IIR1ITHAET2aXA_uDThzSAY',
    appId: '1:905253298603:ios:a33790639ecabcd23072ee',
    messagingSenderId: '905253298603',
    projectId: 'doctor-test-5ddc4',
    storageBucket: 'doctor-test-5ddc4.appspot.com',
    iosClientId: '905253298603-okq9skr2h19pru2j8tqjnns5shohmdbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorTest.RunnerTests',
  );
}
